### ISSUE TITLE
TypeError: Cannot read property 'applications' of undefined

### ISSUE THREAD

**Issue by WeeJeWel** [xat/castv2-youtube#1]
When trying to play a video, I get the following output:

```
found device "weejewel-chromecast" at 192.168.0.119:8009
found device "weejewel-chromecast" at 192.168.0.119:8009
connected, launching app ...
connected, launching app ...

/Users/weejewel/Desktop/node_modules/castv2-client/lib/controllers/receiver.js:50
    callback(null, response.status.applications || []);
                                  ^
TypeError: Cannot read property 'applications' of undefined
    at /Users/weejewel/Desktop/node_modules/castv2-client/lib/controllers/receiver.js:50:35
    at ReceiverController.onmessage (/Users/weejewel/Desktop/node_modules/castv2-client/lib/controllers/request-response.js:27:7)
    at ReceiverController.emit (events.js:117:20)
    at Channel.onmessage (/Users/weejewel/Desktop/node_modules/castv2-client/lib/controllers/controller.js:16:10)
    at Channel.emit (events.js:98:17)
    at Client.onmessage (/Users/weejewel/Desktop/node_modules/castv2-client/node_modules/castv2/lib/channel.js:23:10)
    at Client.emit (events.js:117:20)
    at PacketStreamWrapper.onpacket (/Users/weejewel/Desktop/node_modules/castv2-client/node_modules/castv2/lib/client.js:79:10)
    at PacketStreamWrapper.emit (events.js:95:17)
    at CleartextStream.<anonymous> (/Users/weejewel/Desktop/node_modules/castv2-client/node_modules/castv2/lib/packet-stream-wrapper.js:28:16)
```

**Comment by xat** [comment]
Do you still get that error? Google has changed some stuff lately.

**Comment by WeeJeWel** [comment]
Yep, still the same error!

**Comment by xat** [comment]
I'm wondering why the MDNS scan finds your device twice.

**Comment by WeeJeWel** [comment]
That does not always happen though

**Comment by WeeJeWel** [comment]
Woah, it's working! I guess the chromecast just OTA'd itself! Awesome, thanks.

**Comment by xat** [comment]
:D
