### ISSUE TITLE
Unable to load video on chromecast

### ISSUE THREAD

**Issue by elsewhat** [xat/castv2-youtube#2]
Hi, 

Unable to get the video to play on the youtube chromecast receiver app.
I'm using the sample code from the README.md.

On chromecast, the youtube chromecast receiver app is started, but it doesn't load the video
The output from the script doesn't help much

node view_video.js 
found device "Chromecast6815" at 192.168.1.2:8009
connected, launching app ...

Assume that the youtube chromecast receiver app has been updated by google.
Chromecast is running firmware version:22062

**Comment by xat** [comment]
I think google updated stuff again which seems to make stuff work again :-)
Can you confirm?

**Comment by seflless** [comment]
I have these same symptoms as of today October 24th, 2015. Starts youtube app, gets stuck at screen with huge youtube logo.

**Comment by MatthijsKamstra** [comment]
same here :+1:

**Comment by fxdb** [comment]
YouTube gets stuck at the opening screen; the video does not play

**Comment by matjaz** [comment]
+1

**Comment by WeeJeWel** [comment]
@xat A quick Google Search shows that YouTube has changed their protocol to a session-based queue. Are you planning on adding support for this at all?

**Comment by aniketmhatre88** [comment]
+1

**Comment by hinzundcode** [comment]
+1

**Comment by irfanhabib** [comment]
I've got a fork of this project that supports the new protocol.
https://github.com/irfanhabib/castv2-youtube

**Comment by atishn** [comment]
@irfanhabib There is given issue, even with your repo.


/Users/anarlawar/workspace/voice_assitant_1/node_modules/youtube-castv2-client/YoutubeController.js:102
    return callback(null);
           ^

TypeError: callback is not a function
    at fn.YoutubeController.load (/Users/anarlawar/workspace/voice_assitant_1/node_modules/youtube-castv2-client/YoutubeController.js:102:12)
    at Youtube.load (/Users/anarlawar/workspace/voice_assitant_1/node_modules/youtube-castv2-client/Youtube.js:32:21)
    at /Users/anarlawar/workspace/voice_assitant_1/youtube.js:21:14
